In [1]:
import os
import sys
import itertools
from tqdm import tqdm_notebook as tqdm

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

from matplotlib import pyplot as plt
import matplotlib_venn
import seaborn as sns

import torch
from torch import nn, optim
from transformers import BertConfig, BertTokenizer, BertModel, BertForMaskedLM#, BertLayer, BertEmbeddings
from transformers.modeling_bert import BertLayer, BertEmbeddings

In [2]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

# re-load functions
%load_ext autoreload
%autoreload 2

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:90% !important; }</style>"))
%config InlineBackend.figure_formats = {'png', 'retina'}

In [3]:
DEVICE = 'cpu'

In [4]:
model = BertModel.from_pretrained('bert-base-uncased')

In [9]:
dir(model)

['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_name',
 '_get_resized_embeddings',
 '_init_weights',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_modules',
 '_named_members',
 '_parameters',
 '_prune_heads',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_resize_token_embeddings',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_dict_hooks',
 '_tie_or_clone_weights',
 '_tracing_name',
 '_version',
 'add_module',
 'apply',
 'base_model',
 'base_model_prefix',
 'buffers',
 'children',
 'config',

In [5]:
embeddings = BertEmbeddings(model.config)
print(embeddings.state_dict()['word_embeddings.weight'])
embeddings.load_state_dict(model.embeddings.state_dict())
print(embeddings.state_dict()['word_embeddings.weight'])

tensor([[ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [-0.3070, -0.5426, -1.8465,  ...,  2.0682, -2.6630, -0.9683],
        [-0.5383, -2.1944,  1.4561,  ...,  0.5190, -0.4470,  2.1583],
        ...,
        [-0.6274, -0.7809, -0.3105,  ..., -2.1344,  0.0031,  0.4401],
        [ 0.5369,  0.6548,  1.7529,  ..., -0.1385, -0.3845, -0.4836],
        [ 0.0152,  2.3664,  0.1795,  ...,  1.0437,  0.8664, -0.1354]])
tensor([[-0.0102, -0.0615, -0.0265,  ..., -0.0199, -0.0372, -0.0098],
        [-0.0117, -0.0600, -0.0323,  ..., -0.0168, -0.0401, -0.0107],
        [-0.0198, -0.0627, -0.0326,  ..., -0.0165, -0.0420, -0.0032],
        ...,
        [-0.0218, -0.0556, -0.0135,  ..., -0.0043, -0.0151, -0.0249],
        [-0.0462, -0.0565, -0.0019,  ...,  0.0157, -0.0139, -0.0095],
        [ 0.0015, -0.0821, -0.0160,  ..., -0.0081, -0.0475,  0.0753]])


In [16]:
model.config.is_decoder = True
model.config.is_decoder

True

In [43]:
model.encoder.layer[0].state_dict()

OrderedDict([('attention.self.query.weight',
              tensor([[-0.0164,  0.0261, -0.0263,  ...,  0.0154,  0.0768,  0.0548],
                      [-0.0326,  0.0346, -0.0423,  ..., -0.0527,  0.1393,  0.0078],
                      [ 0.0105,  0.0334,  0.0109,  ..., -0.0279,  0.0258, -0.0468],
                      ...,
                      [-0.0085,  0.0514,  0.0555,  ...,  0.0282,  0.0543, -0.0541],
                      [-0.0198,  0.0944,  0.0617,  ..., -0.1042,  0.0601,  0.0470],
                      [ 0.0015, -0.0952,  0.0099,  ..., -0.0191, -0.0508, -0.0085]])),
             ('attention.self.query.bias',
              tensor([ 5.8489e-01, -3.3124e-01, -4.3010e-01,  3.7446e-01, -2.9812e-01,
                       4.1033e-01,  1.3646e-02,  2.9376e-01,  2.3383e-01, -1.2945e-01,
                       1.3669e-01,  4.5210e-01, -1.0082e-01,  1.1044e-01,  4.3167e-01,
                       5.6541e-01,  3.0794e-02, -4.6629e-02, -3.1482e-01, -1.1942e-01,
                       6.1346e

In [54]:
model.resize_token_embeddings(1000)

Embedding(1000, 768)

In [58]:
embeddings = BertEmbeddings(model.config)

In [59]:
embeddings

BertEmbeddings(
  (word_embeddings): Embedding(1000, 768, padding_idx=0)
  (position_embeddings): Embedding(512, 768)
  (token_type_embeddings): Embedding(2, 768)
  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

In [41]:
layer = BertLayer(model.config)

In [72]:
a =layer(embeddings(torch.tensor([[i for i in range(100)]])))
a

(tensor([[[ 0.5829, -0.0628, -0.6020,  ..., -0.0881, -0.3217,  1.5990],
          [ 2.9984,  0.5932,  0.4470,  ...,  0.4725, -2.2622,  0.5781],
          [ 2.4755,  0.5466,  0.2961,  ...,  0.1181, -1.3945,  1.3181],
          ...,
          [ 0.5575, -0.4348, -1.3788,  ...,  0.3136, -0.6185,  1.5556],
          [ 0.3604,  1.1677, -0.0509,  ...,  0.4154, -0.2616,  0.3257],
          [ 1.7165, -1.3527,  1.4025,  ..., -0.3222,  0.3091, -0.0869]]],
        grad_fn=<NativeLayerNormBackward>),)

In [73]:
a[0].shape

torch.Size([1, 100, 768])

In [76]:
a[0][:, :50, :].shape

torch.Size([1, 50, 768])

In [70]:
BertEmbeddings(BertConfig(vocab_size=30525, max_position_embeddings=1024))

BertEmbeddings(
  (word_embeddings): Embedding(30525, 768, padding_idx=0)
  (position_embeddings): Embedding(1024, 768)
  (token_type_embeddings): Embedding(2, 768)
  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

In [64]:
layer

BertLayer(
  (attention): BertAttention(
    (self): BertSelfAttention(
      (query): Linear(in_features=768, out_features=768, bias=True)
      (key): Linear(in_features=768, out_features=768, bias=True)
      (value): Linear(in_features=768, out_features=768, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (output): BertSelfOutput(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
  (crossattention): BertAttention(
    (self): BertSelfAttention(
      (query): Linear(in_features=768, out_features=768, bias=True)
      (key): Linear(in_features=768, out_features=768, bias=True)
      (value): Linear(in_features=768, out_features=768, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (output): BertSelfOutput(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (LayerNorm): LayerNo

In [52]:
dir(layer)

['__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_name',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_modules',
 '_named_members',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_dict_hooks',
 '_tracing_name',
 '_version',
 'add_module',
 'apply',
 'attention',
 'buffers',
 'children',
 'cpu',
 'crossattention',
 'cuda',
 'double',
 'dump_patches',
 'eval',
 'extra_repr',
 'float',
 'forward',
 'half',
 'intermediate',
 'is_decoder',


In [51]:
dir(embeddings)

['LayerNorm',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_name',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_modules',
 '_named_members',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_dict_hooks',
 '_tracing_name',
 '_version',
 'add_module',
 'apply',
 'buffers',
 'children',
 'cpu',
 'cuda',
 'double',
 'dropout',
 'dump_patches',
 'eval',
 'extra_repr',
 'float',
 'forward',
 'half',
 'load_state_dict',
 'modules',
 'named

In [60]:
trn_df = pd.read_pickle('../mnt/inputs/nes_info/trn_df.pkl')

In [61]:
trn_df.head()

qa_id                                     question_title  \
0      0  What am I losing when using extension tubes in...   
1      1  What is the distinction between a city and a s...   
2      2  Maximum protusion length for through-hole comp...   
3      3              Can an affidavit be used in Beit Din?   
4      5       How do you make a binary image in Photoshop?   

                                       question_body question_user_name  \
0  After playing around with macro photography on...               ysap   
1  I am trying to understand what kinds of places...      russellpierce   
2  I'm working on a PCB that has through-hole com...          Joe Baker   
3  An affidavit, from what i understand, is basic...         Scimonster   
4  I am trying to make a binary image. I want mor...            leigero   

                                  question_user_page  \
0         https://photo.stackexchange.com/users/1024   
1           https://rpg.stackexchange.com/users/8774   
2  https://electronics.stackexchange.com/users/10157   
3       https://judaism.stackexchange.com/users/5151   
4  https://graphicdesign.stackexchange.com/users/...   

                                              answer answer_user_name  \
0  I just got extension tubes, so here's the skin...           rfusca   
1  It might be helpful to look into the definitio...     Erik Schmidt   
2  Do you even need grooves?  We make several pro...      Dwayne Reid   
3  Sending an "affidavit" it is a dispute between...    Y     e     z   
4  Check out Image Trace in Adobe Illustrator. \n...             q2ra   

                                    answer_user_page  \
0         https://photo.stackexchange.com/users/1917   
1           https://rpg.stackexchange.com/users/1871   
2  https://electronics.stackexchange.com/users/64754   
3       https://judaism.stackexchange.com/users/4794   
4  https://graphicdesign.stackexchange.com/users/...   

                                                 url   category  \
0  http://photo.stackexchange.com/questions/9169/...  LIFE_ARTS   
1  http://rpg.stackexchange.com/questions/47820/w...    CULTURE   
2  http://electronics.stackexchange.com/questions...    SCIENCE   
3  http://judaism.stackexchange.com/questions/551...    CULTURE   
4  http://graphicdesign.stackexchange.com/questio...  LIFE_ARTS   

                              host  question_asker_intent_understanding  \
0          photo.stackexchange.com                             1.000000   
1            rpg.stackexchange.com                             1.000000   
2    electronics.stackexchange.com                             0.888889   
3        judaism.stackexchange.com                             0.888889   
4  graphicdesign.stackexchange.com                             1.000000   

   question_body_critical  question_conversational  \
0                0.333333                 0.000000   
1                1.000000                 0.000000   
2                0.666667                 0.000000   
3                0.666667                 0.666667   
4                0.666667                 0.000000   

   question_expect_short_answer  question_fact_seeking  \
0                           0.0                    0.0   
1                           0.5                    1.0   
2                           1.0                    1.0   
3                           1.0                    1.0   
4                           1.0                    1.0   

   question_has_commonly_accepted_answer  question_interestingness_others  \
0                                    0.0                         1.000000   
1                                    1.0                         0.444444   
2                                    1.0                         0.666667   
3                                    1.0                         0.444444   
4                                    1.0                         0.666667   

   question_interestingness_self  question_multi_intent  \
0         

In [62]:
max_len = 0

for i, row in trn_df.iterrows():
    title = row['question_title']
    body = row['question_body']
    answer = row['answer']
    break

In [14]:
for i, j in embeddings.named_children():
    if i == 'position_embeddings':
        break

In [17]:
j.weight = torch.cat([j.weight, j.weight])

TypeError: cannot assign 'torch.FloatTensor' as parameter 'weight' (torch.nn.Parameter or None expected)

In [20]:
torch.cat([j.weight, j.weight]).shape

torch.Size([1024, 768])

In [24]:
dir(j)

['__call__',
 '__class__',
 '__constants__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_buffers',
 '_forward_hooks',
 '_forward_pre_hooks',
 '_get_name',
 '_load_from_state_dict',
 '_load_state_dict_pre_hooks',
 '_modules',
 '_named_members',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_state_dict_hook',
 '_save_to_state_dict',
 '_slow_forward',
 '_state_dict_hooks',
 '_tracing_name',
 '_version',
 'add_module',
 'apply',
 'buffers',
 'children',
 'cpu',
 'cuda',
 'double',
 'dump_patches',
 'embedding_dim',
 'eval',
 'extra_repr',
 'float',
 'forward',
 'from_pretrained',
 'half',
 'load_st

In [28]:
def _resize_embeddings(old_embeddings, new_num_tokens):
    old_num_tokens, old_embedding_dim = old_embeddings.weight.size()
    if old_num_tokens == new_num_tokens:
        return old_embeddings

    # Build new embeddings
    new_embeddings = nn.Embedding(new_num_tokens, old_embedding_dim)
    new_embeddings.to(old_embeddings.weight.device)
 
    # Copy word embeddings from the previous weights
    num_tokens_to_copy = min(old_num_tokens, new_num_tokens)
    new_embeddings.weight.data[:num_tokens_to_copy, :] = old_embeddings.weight.data[:num_tokens_to_copy, :]
 
    return new_embeddings

In [38]:
embeddings.position_embeddings = _resize_embeddings(embeddings.position_embeddings, 1504)

In [40]:
layer

NameError: name 'layer' is not defined

In [39]:
embeddings

BertEmbeddings(
  (word_embeddings): Embedding(30522, 768, padding_idx=0)
  (position_embeddings): Embedding(1504, 768)
  (token_type_embeddings): Embedding(2, 768)
  (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
  (dropout): Dropout(p=0.1, inplace=False)
)

In [32]:
embeddings.children['position_embeddings']

TypeError: 'generator' object is not subscriptable

Embedding(512, 768)

In [51]:
model.embeddings.position_embeddings

Embedding(512, 768)

In [47]:
model.encoder.layer[0]

BertLayer(
  (attention): BertAttention(
    (self): BertSelfAttention(
      (query): Linear(in_features=768, out_features=768, bias=True)
      (key): Linear(in_features=768, out_features=768, bias=True)
      (value): Linear(in_features=768, out_features=768, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (output): BertSelfOutput(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
  (intermediate): BertIntermediate(
    (dense): Linear(in_features=768, out_features=3072, bias=True)
  )
  (output): BertOutput(
    (dense): Linear(in_features=3072, out_features=768, bias=True)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
)

In [42]:
layer

BertLayer(
  (attention): BertAttention(
    (self): BertSelfAttention(
      (query): Linear(in_features=768, out_features=768, bias=True)
      (key): Linear(in_features=768, out_features=768, bias=True)
      (value): Linear(in_features=768, out_features=768, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (output): BertSelfOutput(
      (dense): Linear(in_features=768, out_features=768, bias=True)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
  )
  (intermediate): BertIntermediate(
    (dense): Linear(in_features=768, out_features=3072, bias=True)
  )
  (output): BertOutput(
    (dense): Linear(in_features=3072, out_features=768, bias=True)
    (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
)